local: false
service:
  name: "RAILWAY_SERVICE_NAME"   # Placeholder for environment variable
  id: "RAILWAY_SERVICE_ID"       # Placeholder for environment variable
server:
  port: "8080"
  URL: "slash-proxy-production.up.railway.app"
proxy:
  registration_url: "https://slash-proxy-production.up.railway.app/webservers/register"
