name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Build Docker image
        run: |
          docker build -t websocket-server .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag websocket-server ${{ secrets.DOCKER_USERNAME }}/websocket-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/websocket-server:latest

      - name: Connect to EC2 and run Docker container
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@ec2-16-171-141-188.eu-north-1.compute.amazonaws.com << 'EOF'
            # Pull the latest image from Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/websocket-server:latest
            
            # Stop and remove the existing container if it's running
            sudo docker stop websocket-server || true
            sudo docker rm websocket-server || true
            
            # Run the Docker container with network bridge on port 8080
            sudo docker run -d -p 8080:8080 --name websocket-server --network bridge ${{ secrets.DOCKER_USERNAME }}/websocket-server:latest
          EOF
